version: "3.9"

services:
  custom-countries:
    build: .
    ports:
      - "5000:80"
#     volumes:
#       - .:/code
#       - logvolume01:/var/log
#     links:
#       - redis
#   redis:
#     image: redis
# volumes:
#   logvolume01: {}